[package]
name = "cuckoo_map"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
whyhash = { path = "../whyhash" }

[profile.test]
opt-level = 3
